import { Item } from "@/types/item";

// Temporary mock dataset for UI development.
// Will be replaced by the real /api/items response once the backend exists.
export const mockItems: Item[] = [
  {
    id: "1",
    title: "Black North Face Backpack",
    description:
      "Left in the CS building lecture hall, has a laptop sleeve and a small keychain on the zipper.",
    type: "lost",
    category: "bags",
    location: "Computer Science Building",
    date: "2026-09-06",
    imageUrl: "https://picsum.photos/seed/backpack/600/400",
    status: "active",
    postedBy: { id: "u1", name: "Aditi R." },
  },
  {
    id: "2",
    title: "Silver Hydro Flask Bottle",
    description: "Found near the library entrance, has a sticker on the cap.",
    type: "found",
    category: "other",
    location: "Library",
    date: "2026-09-05",
    imageUrl: "https://picsum.photos/seed/bottle/600/400",
    status: "active",
    postedBy: { id: "u2", name: "Marcus T." },
  },
  {
    id: "3",
    title: "Set of Keys with Blue Lanyard",
    description: "Dorm and bike lock keys found near the gym entrance.",
    type: "found",
    category: "keys",
    location: "Recreation Center",
    date: "2026-09-04",
    imageUrl: "https://picsum.photos/seed/keys/600/400",
    status: "active",
    postedBy: { id: "u3", name: "Priya S." },
  },
  {
    id: "4",
    title: "iPad Air with Blue Case",
    description: "Lost during lunch at the student union food court.",
    type: "lost",
    category: "electronics",
    location: "Student Union",
    date: "2026-09-03",
    imageUrl: "https://picsum.photos/seed/tablet/600/400",
    status: "resolved",
    postedBy: { id: "u4", name: "Leo M." },
  },
  {
    id: "5",
    title: "Student ID Card - Priya Nair",
    description: "Found on a cafeteria table near the drinks counter.",
    type: "found",
    category: "documents",
    location: "Cafeteria",
    date: "2026-09-02",
    imageUrl: "https://picsum.photos/seed/idcard/600/400",
    status: "active",
    postedBy: { id: "u5", name: "Sam K." },
  },
  {
    id: "6",
    title: "Grey Wool Scarf",
    description: "Left behind in Lecture Hall B after the 2pm seminar.",
    type: "lost",
    category: "clothing",
    location: "Lecture Hall Complex",
    date: "2026-09-01",
    imageUrl: "https://picsum.photos/seed/scarf/600/400",
    status: "active",
    postedBy: { id: "u6", name: "Nina P." },
  },
  {
    id: "7",
    title: "Introduction to Algorithms Textbook",
    description: "Found in the parking lot near the east entrance, has handwritten notes inside.",
    type: "found",
    category: "books",
    location: "Parking Lot",
    date: "2026-08-30",
    imageUrl: "https://picsum.photos/seed/textbook/600/400",
    status: "active",
    postedBy: { id: "u7", name: "Owen D." },
  },
  {
    id: "8",
    title: "Wired Earbuds, White",
    description: "Lost somewhere between the dorms and the CS building.",
    type: "lost",
    category: "electronics",
    location: "Dormitories",
    date: "2026-08-29",
    imageUrl: "https://picsum.photos/seed/earbuds/600/400",
    status: "active",
    postedBy: { id: "u8", name: "Farah H." },
  },
  {
    id: "9",
    title: "Black Leather Wallet",
    description: "Found near the recreation center entrance, contains a gym card.",
    type: "found",
    category: "accessories",
    location: "Recreation Center",
    date: "2026-08-28",
    imageUrl: "https://picsum.photos/seed/wallet/600/400",
    status: "resolved",
    postedBy: { id: "u9", name: "Diego M." },
  },
  {
    id: "10",
    title: "Prescription Glasses, Tortoiseshell",
    description: "Left on a table in the library's second-floor study area.",
    type: "lost",
    category: "accessories",
    location: "Library",
    date: "2026-08-27",
    imageUrl: "https://picsum.photos/seed/glasses/600/400",
    status: "active",
    postedBy: { id: "u10", name: "Grace L." },
  },
  {
    id: "11",
    title: "Blue Umbrella",
    description: "Found propped against a chair in the student union lounge.",
    type: "found",
    category: "other",
    location: "Student Union",
    date: "2026-08-26",
    imageUrl: "https://picsum.photos/seed/umbrella/600/400",
    status: "active",
    postedBy: { id: "u11", name: "Ken W." },
  },
  {
    id: "12",
    title: "Red Denim Jacket",
    description: "Lost after the outdoor orientation event near the cafeteria.",
    type: "lost",
    category: "clothing",
    location: "Cafeteria",
    date: "2026-08-25",
    imageUrl: "https://picsum.photos/seed/jacket/600/400",
    status: "active",
    postedBy: { id: "u12", name: "Zara B." },
  },
];

export const mockStats = [
  { label: "Items reported", value: 482 },
  { label: "Items reunited", value: 317 },
  { label: "Active this week", value: 41 },
];